#!/usr/bin/env python3
"""Generate or verify the markdown indexes.

  INDEX.md (plugin root)    the catalog's own vocabulary -- product names and
                            keywords, style ids, font pairings, landing pattern
                            ids, stacks -- plus the data files and references. A
                            search only matches the words the catalog uses, and
                            nothing else lists them.
  INDEX.md (ROSW root)      only when the plugin sits inside the ROSW
                            monorepo, as plugins/ui-design/: the tools, and every
                            skill and agent, read from each one's frontmatter.
                            Nothing under creative-writing/ is edited to produce
                            it. In the published plugin repository there is no
                            such file, and only the plugin index is handled.

Every index is generated from the live data and frontmatter, so it cannot drift:
--check regenerates in memory and fails on any difference, and names a skill or
agent that is missing from the root index. verify.py runs it as a gate.

Usage:
    python maintenance/generate-index.py           # write the index or indexes
    python maintenance/generate-index.py --check   # verify, write nothing
(run from the plugin root, or give the path from anywhere)

Exit codes:
    0 -- written, or --check found every index current
    2 -- --check found a stale or missing index, or an input is unreadable
         (pyyaml missing, a data file with no declared purpose, a tool folder
         with no declared purpose)
"""

import argparse
import csv
import re
import sys
from pathlib import Path

TOOL_ROOT = Path(__file__).resolve().parents[1]      # the plugin root
DATA = TOOL_ROOT / "catalog" / "data"
REFERENCES = TOOL_ROOT / "references"
TOOL_INDEX = TOOL_ROOT / "INDEX.md"


def find_monorepo_root():
    """The ROSW root when this plugin is checked out as plugins/<name>/, else None."""
    if TOOL_ROOT.parent.name != "plugins":
        return None
    candidate = TOOL_ROOT.parents[1]
    return candidate if (candidate / "CLAUDE.md").is_file() else None


REPO_ROOT = find_monorepo_root()
ROOT_INDEX = REPO_ROOT / "INDEX.md" if REPO_ROOT else None

REGENERATE = "python maintenance/generate-index.py"
HEADER = ("<!-- Generated by maintenance/generate-index.py -- do not edit by hand.\n"
          "     Regenerate with: " + REGENERATE + " (from the plugin root) -->\n")
ROOT_REGENERATE = "python plugins/ui-design/maintenance/generate-index.py"
ROOT_HEADER = ("<!-- Generated by plugins/ui-design/maintenance/generate-index.py -- do not edit by hand.\n"
               "     Regenerate with: " + ROOT_REGENERATE + " -->\n")

# What each catalog data file is for. A file missing from here fails the run,
# so a new CSV cannot land without a purpose.
DATA_PURPOSE = {
    "products.csv": "Product types: the row `--design-system` and `--domain product` resolve a brief to.",
    "styles.csv": "Visual styles, with status (active, supplemental, deprecated) and aliases.",
    "colors.csv": "One palette per product type, with on-colors, for the WCAG 2.2 contrast check.",
    "typography.csv": "Named font pairings with mood keywords and import snippets.",
    "landing.csv": "Landing page patterns, by pattern id, with section order and CTA placement.",
    "ux-guidelines.csv": "UX guidelines by category, with Do / Don't and severity.",
    "charts.csv": "Chart type recommendations by data type, with accessibility grade.",
    "icons.csv": "Curated icon rows (Phosphor) with semantic role and allowed contexts.",
    "motion.csv": "GSAP motion presets by intensity tier, with spring and reduced-motion variants.",
    "react-performance.csv": "React / Next.js performance rules.",
    "app-interface.csv": "App and native interface guidelines.",
    "ui-reasoning.csv": "Reasoning profile per product type that steers the design-system generator.",
    "google-fonts.csv": "The approved Google Fonts catalog.",
    "catalog-summary.json": "Generated counts and snapshot hashes (generate-catalog-summary.py).",
    "data-provenance.json": "Provenance and licensing of the data.",
    "google-font-licenses.json": "Per-family Google Fonts licenses and exclusions.",
    "phosphor-icons-upstream.json": "The upstream Phosphor icon manifest.",
}

# What each top-level tool folder is for. Hidden folders (.claude, .obsidian) are skipped.
TOOL_PURPOSE = {
    "creative-writing": "The Obsidian vault of 63 works plus the checkpointed pipeline that writes into it.",
    "docs": "Browsable HTML pages describing each tool, and a local helper for setting API keys.",
    "plugins": "Claude Code plugins, each self-contained and shippable on its own. Today: ui-design, "
               "a local BM25 catalog of UI styles, palettes, fonts, UX rules, icons, motion and stacks, "
               "with a design-system generator; and blender, skills for driving a live Blender through MCP.",
    "studio": "Checkpointed production pipelines and the notes they leave behind.",
    "writing-museum": "A walkable 3D museum of the creative-writing vault, one room per work, built "
                      "through the studio's scene-3d pipeline.",
}

REFERENCE_PURPOSE = {
    "quick-reference.md": "Every rule in ten categories, by rule-id; the source the page reviewer cites.",
    "pro-rules.md": "Native/mobile app polish rules and the pre-delivery checklist.",
}


class IndexError_(Exception):
    """An input the index cannot be built from."""


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def read_rows(path):
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def distinct(rows, column):
    return list(dict.fromkeys(row[column] for row in rows if row.get(column)))


def table(headers, body):
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    lines += ["| " + " | ".join(cell(c) for c in row) + " |" for row in body]
    return lines


def domain_of_file():
    sys.path.insert(0, str(TOOL_ROOT / "catalog" / "scripts"))
    import core
    return {config["file"]: domain for domain, config in core.CSV_CONFIG.items()}, core.AVAILABLE_STACKS


def build_tool_index():
    file_domain, stacks = domain_of_file()
    out = [HEADER, "# ui-design index", "",
           "The catalog's own vocabulary. A search matches the words the catalog uses, "
           "not the words a brief happens to use: `invoicing` finds nothing useful where "
           "`invoice` finds the right row. Phrase queries with the names below, or run "
           "`python \"<plugin-root>/catalog/scripts/route.py\" \"<brief>\"` to have that done for you "
           "(`<plugin-root>` is the absolute path your skill names as `${CLAUDE_PLUGIN_ROOT}`). "
           "How to choose a mode and a domain is in [ROUTER.md](ROUTER.md).", ""]

    out += ["## Data files", ""]
    body = []
    for path in sorted(DATA.glob("*.csv")) + sorted(DATA.glob("*.json")):
        if path.name not in DATA_PURPOSE:
            raise IndexError_(f"{path.name} has no entry in DATA_PURPOSE (generate-index.py)")
        count = len(read_rows(path)) if path.suffix == ".csv" else "-"
        body.append([f"`catalog/data/{path.name}`", count, file_domain.get(path.name, "-"),
                     DATA_PURPOSE[path.name]])
    stack_files = sorted((DATA / "stacks").glob("*.csv"))
    body.append([f"`catalog/data/stacks/*.csv` ({len(stack_files)} files)",
                 sum(len(read_rows(p)) for p in stack_files), "--stack",
                 "One guideline file per stack."])
    out += table(["File", "Rows", "Domain", "Purpose"], body) + [""]

    products = read_rows(DATA / "products.csv")
    out += [f"## Products ({len(products)})", "",
            "Words to use for `--domain product`, `--design-system` and `--domain color` "
            "(palettes are keyed by the same product types).", ""]
    out += table(["id", "Product type", "Keywords"],
                 [[p["No"], p["Product Type"], p["Keywords"]] for p in products]) + [""]

    styles = [s for s in read_rows(DATA / "styles.csv") if s.get("Status") != "deprecated"]
    out += [f"## Styles ({len(styles)} searchable)", ""]
    out += table(["Style id", "Category", "Status"],
                 [[s["Style ID"], s["Style Category"], s["Status"]] for s in styles]) + [""]

    typography = read_rows(DATA / "typography.csv")
    out += [f"## Font pairings ({len(typography)})", ""]
    out += table(["Pairing", "Category"],
                 [[t["Font Pairing Name"], t["Category"]] for t in typography]) + [""]

    landing = read_rows(DATA / "landing.csv")
    out += [f"## Landing patterns ({len(landing)})", ""]
    out += table(["Pattern id", "Name"], [[l["Pattern ID"], l["Pattern Name"]] for l in landing]) + [""]

    out += ["## Other vocabularies", ""]
    for label, filename, column in (
            ("UX guideline categories", "ux-guidelines.csv", "Category"),
            ("Chart data types", "charts.csv", "Data Type"),
            ("Icon categories", "icons.csv", "Category"),
            ("Motion categories", "motion.csv", "Category")):
        values = distinct(read_rows(DATA / filename), column)
        out.append(f"- **{label}** ({len(values)}): " + ", ".join(values))
    out += ["", "## Stacks", "", ", ".join(f"`{s}`" for s in stacks), ""]

    out += ["## References", "",
            "Prose read on demand; not searched.", ""]
    body = []
    for path in sorted(REFERENCES.glob("*.md")):
        if path.name not in REFERENCE_PURPOSE:
            raise IndexError_(f"references/{path.name} has no entry in REFERENCE_PURPOSE (generate-index.py)")
        body.append([f"[references/{path.name}](references/{path.name})", REFERENCE_PURPOSE[path.name]])
    out += table(["File", "Purpose"], body) + [""]

    out += ["## Also here", "",
            "- [ROUTER.md](ROUTER.md): pick a search mode, a domain and a query; what to do when a match looks wrong.",
            "- [spec.yaml](spec.yaml): the declared contract (domains, stacks, formats, dials, exit codes).",
            ""]
    return "\n".join(out)


def load_yaml():
    try:
        import yaml
    except ImportError as exc:
        raise IndexError_("pyyaml is required to read skill and agent frontmatter: pip install pyyaml") from exc
    return yaml


def shown(path):
    """A path as a reader of an error message should see it."""
    base = REPO_ROOT or TOOL_ROOT
    return path.relative_to(base).as_posix()


def frontmatter(yaml, path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise IndexError_(f"{shown(path)}: no YAML frontmatter")
    end = text.find("\n---", 3)
    data = yaml.safe_load(text[3:end]) if end != -1 else None
    if not isinstance(data, dict) or not data.get("name") or not data.get("description"):
        raise IndexError_(f"{shown(path)}: frontmatter needs name and description")
    return data


def first_sentence(description, limit=280):
    flat = " ".join(str(description).split())
    match = re.search(r"(?<=[a-z0-9)`])\.\s", flat)
    sentence = flat[: match.start() + 1] if match else flat
    return sentence if len(sentence) <= limit else sentence[: limit - 3].rstrip() + "..."


def collect_entries():
    """Every skill and agent the index covers: the plugin's own, and in the
    monorepo also the root .claude/ ones and those of any sibling plugin."""
    yaml = load_yaml()
    if REPO_ROOT:
        skill_paths = (sorted((REPO_ROOT / ".claude" / "skills").glob("*/SKILL.md"))
                       + sorted((REPO_ROOT / "plugins").glob("*/skills/*/SKILL.md")))
        agent_paths = (sorted((REPO_ROOT / ".claude" / "agents").glob("*.md"))
                       + sorted((REPO_ROOT / "plugins").glob("*/agents/*.md")))
    else:
        skill_paths = sorted((TOOL_ROOT / "skills").glob("*/SKILL.md"))
        agent_paths = sorted((TOOL_ROOT / "agents").glob("*.md"))
    return ([(frontmatter(yaml, p), p) for p in skill_paths],
            [(frontmatter(yaml, p), p) for p in agent_paths])


def build_root_index():
    if not REPO_ROOT:
        raise IndexError_("the ROSW root index only exists when the plugin is checked out "
                          "as plugins/<name>/ inside the ROSW repo")
    skills, agents = collect_entries()
    out = [ROOT_HEADER, "# ROSW index", "",
           "One repo, several tools. Each tool is a self-contained folder: `creative-writing/`, "
           "`studio/`, and each Claude Code plugin under `plugins/`. The creative-writing and "
           "studio skills and agents live once, here at the root, under `.claude/`; a plugin "
           "carries its own `skills/` and "
           "`agents/`, so it can be published on its own. Conventions are in "
           "[CLAUDE.md](CLAUDE.md), the overview in [README.md](README.md).", "",
           "## Tools", ""]
    body = []
    # Git does not track empty folders, so one left behind by a move must not make the
    # index differ between this checkout and a fresh clone.
    for path in sorted(p for p in REPO_ROOT.iterdir()
                       if p.is_dir() and not p.name.startswith(".") and any(p.iterdir())):
        if path.name not in TOOL_PURPOSE:
            raise IndexError_(f"top-level folder {path.name}/ has no entry in TOOL_PURPOSE (generate-index.py)")
        entry = "[plugins/ui-design/INDEX.md](plugins/ui-design/INDEX.md)" if path.name == "plugins" else "-"
        body.append([f"`{path.name}/`", TOOL_PURPOSE[path.name], entry])
    out += table(["Folder", "Purpose", "Index"], body) + ["", f"## Skills ({len(skills)})", ""]
    out += table(["Skill", "What it does"],
                 [[f"[{fm['name']}]({shown(p)})", first_sentence(fm["description"])]
                  for fm, p in skills]) + ["", f"## Agents ({len(agents)})", ""]
    out += table(["Agent", "What it does"],
                 [[f"[{fm['name']}]({shown(p)})", first_sentence(fm["description"])]
                  for fm, p in agents]) + [""]
    return "\n".join(out)


def missing_from_root(text):
    skills, agents = collect_entries()
    return [fm["name"] for fm, _ in skills + agents if f"[{fm['name']}]" not in text]


def read_text(path):
    return path.read_text(encoding="utf-8") if path.exists() else None


def main():
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except AttributeError:
            pass
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify both indexes are current; write nothing")
    args = parser.parse_args()
    try:
        generated = {TOOL_INDEX: build_tool_index() + "\n"}
        if ROOT_INDEX:
            generated[ROOT_INDEX] = build_root_index() + "\n"
        if args.check:
            problems = []
            for path, content in generated.items():
                current = read_text(path)
                name = shown(path)
                if current is None:
                    problems.append(f"{name} is missing")
                elif current != content:
                    problems.append(f"{name} is stale")
            root_text = read_text(ROOT_INDEX) if ROOT_INDEX else None
            if root_text is not None:
                absent = missing_from_root(root_text)
                if absent:
                    problems.append("INDEX.md does not list: " + ", ".join(absent))
            if problems:
                raise IndexError_("; ".join(problems) + f". Regenerate with: {REGENERATE}"
                                  + (f" (from the ROSW root: {ROOT_REGENERATE})" if ROOT_INDEX else ""))
        else:
            for path, content in generated.items():
                path.write_text(content, encoding="utf-8", newline="\n")
    except (IndexError_, OSError, KeyError) as exc:
        print(f"generate-index: {exc}", file=sys.stderr)
        return 2
    written = "INDEX.md" + (" and the ROSW root INDEX.md" if ROOT_INDEX else "")
    print("Indexes are current." if args.check else f"Generated {written}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
