#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
shadcn/ui theme exporter - emits a generated design system as the CSS variable
block shadcn/ui/Tailwind v4 expects, drop-in compatible with tweakcn themes.

    from design_system import generate_design_system
    from shadcn_theme import to_shadcn_css

    result = generate_design_system("SaaS dashboard", "My Project")
    print(to_shadcn_css(result["design_system"]))

Paste the output into `globals.css`. Values are `oklch(L C H)`, matching
shadcn/ui v4 and tweakcn; pass `color_format="hex"` for the older hex contract.

WHAT IS AND IS NOT EMITTED
--------------------------
shadcn's full contract has variables this generator has no data for. Rather
than inventing them:
  * `popover` / `popover-foreground` alias `card` / `card-foreground`, and
    `input` aliases `border`. These are conventional aliases, marked in the
    output, not guesses.
  * `chart-1..5` and the `sidebar-*` family are OMITTED. Fabricating five
    categorical chart colors from a three-color brand palette would produce
    something that looks authoritative and is not. Emitting nothing leaves
    shadcn's own defaults in place, which is the honest fallback.
"""

from contrast import advisories, evaluate_palette, failures
from oklch import format_oklch

# (shadcn variable, design system colors key, aliased-from or None)
LIGHT_MAPPING = (
    ("background", "background", None),
    ("foreground", "foreground", None),
    ("card", "card", None),
    ("card-foreground", "card_foreground", None),
    ("popover", "card", "card"),
    ("popover-foreground", "card_foreground", "card-foreground"),
    ("primary", "primary", None),
    ("primary-foreground", "on_primary", None),
    ("secondary", "secondary", None),
    ("secondary-foreground", "on_secondary", None),
    ("muted", "muted", None),
    ("muted-foreground", "muted_foreground", None),
    ("accent", "accent", None),
    ("accent-foreground", "on_accent", None),
    ("destructive", "destructive", None),
    ("destructive-foreground", "on_destructive", None),
    ("border", "border", None),
    ("input", "border", "border"),
    ("ring", "ring", None),
)

# shadcn exposes one --radius that its components scale from. Not data-driven
# here, so it matches the shadcn default rather than pretending to be derived.
DEFAULT_RADIUS = "0.625rem"

OMITTED_NOTE = (
    "chart-1..5 and sidebar-* are intentionally omitted: this design system "
    "has no data for them, and inventing them would be worse than inheriting "
    "shadcn's defaults."
)


def _format_value(hex_color: str, color_format: str):
    if color_format == "hex":
        return hex_color
    return format_oklch(hex_color)


def to_shadcn_css(design_system: dict, color_format: str = "oklch") -> str:
    """Render the `:root` block for a design system.

    color_format: "oklch" (default, shadcn v4 / tweakcn) or "hex".
    """
    if color_format not in ("oklch", "hex"):
        raise ValueError(f"unsupported color_format: {color_format!r}")

    colors = design_system.get("colors", {})
    project = design_system.get("project_name", "PROJECT")
    style = design_system.get("style", {}).get("name", "")

    lines = [
        f"/* {project} - shadcn/ui theme"
        + (f" ({style})" if style else ""),
        "   Generated by UI UX Pro Max. Paste into globals.css.",
        f"   {OMITTED_NOTE} */",
        ":root {",
        f"  --radius: {DEFAULT_RADIUS};",
    ]

    skipped = []
    for variable, key, alias_of in LIGHT_MAPPING:
        hex_color = (colors.get(key) or "").strip()
        if not hex_color:
            skipped.append(variable)
            continue
        value = _format_value(hex_color, color_format)
        if value is None:
            skipped.append(variable)
            continue
        comment = f"  /* alias of --{alias_of} */" if alias_of else ""
        lines.append(f"  --{variable}: {value};{comment}")

    lines.append("}")

    if skipped:
        lines.append("")
        lines.append(
            "/* Not emitted (no value in the source palette): "
            + ", ".join(f"--{name}" for name in skipped)
            + " */"
        )

    report = design_system.get("contrast") or evaluate_palette(colors)
    blocking = failures(report)
    advisory = advisories(report)
    if blocking or advisory:
        lines.append("")
        lines.append("/* Contrast notes (WCAG 2.2):")
        for entry in blocking:
            lines.append(
                f"     FAIL {entry['label']}: {entry['ratio']}:1 "
                f"(needs {entry['wcag22Minimum']}:1)"
            )
        for entry in advisory:
            lines.append(
                f"     warn {entry['label']}: {entry['ratio']}:1 "
                f"(needs {entry['wcag22Minimum']}:1, non-text/advisory)"
            )
        lines.append("   */")

    return "\n".join(lines) + "\n"
