#!/usr/bin/env python3
"""Generate or verify the two markdown indexes: ui-design/INDEX.md and INDEX.md.

  ui-design/INDEX.md   the catalog's own vocabulary -- product names and
                       keywords, style ids, font pairings, landing pattern
                       ids, stacks -- plus the data files and references. A
                       search only matches the words the catalog uses, and
                       nothing else lists them.
  INDEX.md (repo root) the tools, and every skill and agent, read from each
                       one's frontmatter. Nothing under creative-writing/ is
                       edited to produce it.

Both are generated from the live data and frontmatter, so they cannot drift:
--check regenerates in memory and fails on any difference, and names a skill or
agent that is missing from the root index. verify.py runs it as a gate.

Usage:
    python ui-design/maintenance/generate-index.py           # write both files
    python ui-design/maintenance/generate-index.py --check   # verify, write nothing

Exit codes:
    0 -- written, or --check found both indexes current
    2 -- --check found a stale or missing index, or an input is unreadable
         (pyyaml missing, a data file with no declared purpose, a tool folder
         with no declared purpose)
"""

import argparse
import csv
import re
import sys
from pathlib import Path

TOOL_ROOT = Path(__file__).resolve().parents[1]      # ui-design/
REPO_ROOT = TOOL_ROOT.parent
DATA = TOOL_ROOT / "catalog" / "data"
REFERENCES = TOOL_ROOT / "references"
SKILLS = REPO_ROOT / ".claude" / "skills"
AGENTS = REPO_ROOT / ".claude" / "agents"
TOOL_INDEX = TOOL_ROOT / "INDEX.md"
ROOT_INDEX = REPO_ROOT / "INDEX.md"

REGENERATE = "python ui-design/maintenance/generate-index.py"
HEADER = ("<!-- Generated by ui-design/maintenance/generate-index.py -- do not edit by hand.\n"
          "     Regenerate with: " + REGENERATE + " -->\n")

# What each catalog data file is for. A file missing from here fails the run,
# so a new CSV cannot land without a purpose.
DATA_PURPOSE = {
    "products.csv": "Product types: the row `--design-system` and `--domain product` resolve a brief to.",
    "styles.csv": "Visual styles, with status (active, supplemental, deprecated) and aliases.",
    "colors.csv": "One palette per product type, with on-colors, for the WCAG 2.2 contrast check.",
    "typography.csv": "Named font pairings with mood keywords and import snippets.",
    "landing.csv": "Landing page patterns, by pattern id, with section order and CTA placement.",
    "ux-guidelines.csv": "UX guidelines by category, with Do / Don't and severity.",
    "charts.csv": "Chart type recommendations by data type, with accessibility grade.",
    "icons.csv": "Curated icon rows (Phosphor) with semantic role and allowed contexts.",
    "motion.csv": "GSAP motion presets by intensity tier, with spring and reduced-motion variants.",
    "react-performance.csv": "React / Next.js performance rules.",
    "app-interface.csv": "App and native interface guidelines.",
    "ui-reasoning.csv": "Reasoning profile per product type that steers the design-system generator.",
    "google-fonts.csv": "The approved Google Fonts catalog.",
    "catalog-summary.json": "Generated counts and snapshot hashes (generate-catalog-summary.py).",
    "data-provenance.json": "Provenance and licensing of the data.",
    "google-font-licenses.json": "Per-family Google Fonts licenses and exclusions.",
    "phosphor-icons-upstream.json": "The upstream Phosphor icon manifest.",
}

# What each top-level tool folder is for. Hidden folders (.claude, .obsidian) are skipped.
TOOL_PURPOSE = {
    "creative-writing": "The Obsidian vault of 63 works plus the checkpointed pipeline that writes into it.",
    "ui-design": "A local BM25 catalog of UI styles, palettes, fonts, UX rules, icons, motion and stacks, "
                 "with a design-system generator.",
}

REFERENCE_PURPOSE = {
    "quick-reference.md": "Every rule in ten categories, by rule-id; the source the page reviewer cites.",
    "pro-rules.md": "Native/mobile app polish rules and the pre-delivery checklist.",
}


class IndexError_(Exception):
    """An input the index cannot be built from."""


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def read_rows(path):
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def distinct(rows, column):
    return list(dict.fromkeys(row[column] for row in rows if row.get(column)))


def table(headers, body):
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    lines += ["| " + " | ".join(cell(c) for c in row) + " |" for row in body]
    return lines


def domain_of_file():
    sys.path.insert(0, str(TOOL_ROOT / "catalog" / "scripts"))
    import core
    return {config["file"]: domain for domain, config in core.CSV_CONFIG.items()}, core.AVAILABLE_STACKS


def build_tool_index():
    file_domain, stacks = domain_of_file()
    out = [HEADER, "# ui-design index", "",
           "The catalog's own vocabulary. A search matches the words the catalog uses, "
           "not the words a brief happens to use: `invoicing` finds nothing useful where "
           "`invoice` finds the right row. Phrase queries with the names below, or run "
           "`python ui-design/catalog/scripts/route.py \"<brief>\"` to have that done for you. "
           "How to choose a mode and a domain is in [ROUTER.md](ROUTER.md).", ""]

    out += ["## Data files", ""]
    body = []
    for path in sorted(DATA.glob("*.csv")) + sorted(DATA.glob("*.json")):
        if path.name not in DATA_PURPOSE:
            raise IndexError_(f"{path.name} has no entry in DATA_PURPOSE (generate-index.py)")
        count = len(read_rows(path)) if path.suffix == ".csv" else "-"
        body.append([f"`catalog/data/{path.name}`", count, file_domain.get(path.name, "-"),
                     DATA_PURPOSE[path.name]])
    stack_files = sorted((DATA / "stacks").glob("*.csv"))
    body.append([f"`catalog/data/stacks/*.csv` ({len(stack_files)} files)",
                 sum(len(read_rows(p)) for p in stack_files), "--stack",
                 "One guideline file per stack."])
    out += table(["File", "Rows", "Domain", "Purpose"], body) + [""]

    products = read_rows(DATA / "products.csv")
    out += [f"## Products ({len(products)})", "",
            "Words to use for `--domain product`, `--design-system` and `--domain color` "
            "(palettes are keyed by the same product types).", ""]
    out += table(["id", "Product type", "Keywords"],
                 [[p["No"], p["Product Type"], p["Keywords"]] for p in products]) + [""]

    styles = [s for s in read_rows(DATA / "styles.csv") if s.get("Status") != "deprecated"]
    out += [f"## Styles ({len(styles)} searchable)", ""]
    out += table(["Style id", "Category", "Status"],
                 [[s["Style ID"], s["Style Category"], s["Status"]] for s in styles]) + [""]

    typography = read_rows(DATA / "typography.csv")
    out += [f"## Font pairings ({len(typography)})", ""]
    out += table(["Pairing", "Category"],
                 [[t["Font Pairing Name"], t["Category"]] for t in typography]) + [""]

    landing = read_rows(DATA / "landing.csv")
    out += [f"## Landing patterns ({len(landing)})", ""]
    out += table(["Pattern id", "Name"], [[l["Pattern ID"], l["Pattern Name"]] for l in landing]) + [""]

    out += ["## Other vocabularies", ""]
    for label, filename, column in (
            ("UX guideline categories", "ux-guidelines.csv", "Category"),
            ("Chart data types", "charts.csv", "Data Type"),
            ("Icon categories", "icons.csv", "Category"),
            ("Motion categories", "motion.csv", "Category")):
        values = distinct(read_rows(DATA / filename), column)
        out.append(f"- **{label}** ({len(values)}): " + ", ".join(values))
    out += ["", "## Stacks", "", ", ".join(f"`{s}`" for s in stacks), ""]

    out += ["## References", "",
            "Prose read on demand; not searched.", ""]
    body = []
    for path in sorted(REFERENCES.glob("*.md")):
        if path.name not in REFERENCE_PURPOSE:
            raise IndexError_(f"references/{path.name} has no entry in REFERENCE_PURPOSE (generate-index.py)")
        body.append([f"[references/{path.name}](references/{path.name})", REFERENCE_PURPOSE[path.name]])
    out += table(["File", "Purpose"], body) + [""]

    out += ["## Also here", "",
            "- [ROUTER.md](ROUTER.md): pick a search mode, a domain and a query; what to do when a match looks wrong.",
            "- [spec.yaml](spec.yaml): the declared contract (domains, stacks, formats, dials, exit codes).",
            ""]
    return "\n".join(out)


def load_yaml():
    try:
        import yaml
    except ImportError as exc:
        raise IndexError_("pyyaml is required to read skill and agent frontmatter: pip install pyyaml") from exc
    return yaml


def frontmatter(yaml, path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise IndexError_(f"{path.relative_to(REPO_ROOT).as_posix()}: no YAML frontmatter")
    end = text.find("\n---", 3)
    data = yaml.safe_load(text[3:end]) if end != -1 else None
    if not isinstance(data, dict) or not data.get("name") or not data.get("description"):
        raise IndexError_(f"{path.relative_to(REPO_ROOT).as_posix()}: frontmatter needs name and description")
    return data


def first_sentence(description, limit=280):
    flat = " ".join(str(description).split())
    match = re.search(r"(?<=[a-z0-9)`])\.\s", flat)
    sentence = flat[: match.start() + 1] if match else flat
    return sentence if len(sentence) <= limit else sentence[: limit - 3].rstrip() + "..."


def collect_entries():
    yaml = load_yaml()
    skills = [(frontmatter(yaml, p), p) for p in sorted(SKILLS.glob("*/SKILL.md"))]
    agents = [(frontmatter(yaml, p), p) for p in sorted(AGENTS.glob("*.md"))]
    return skills, agents


def build_root_index():
    skills, agents = collect_entries()
    out = [HEADER, "# Pipelines index", "",
           "One repo, several tools. Each tool is a self-contained top-level folder; skills "
           "and agents live once, here at the root, under `.claude/`. Conventions are in "
           "[CLAUDE.md](CLAUDE.md), the overview in [README.md](README.md).", "",
           "## Tools", ""]
    body = []
    for path in sorted(p for p in REPO_ROOT.iterdir() if p.is_dir() and not p.name.startswith(".")):
        if path.name not in TOOL_PURPOSE:
            raise IndexError_(f"top-level folder {path.name}/ has no entry in TOOL_PURPOSE (generate-index.py)")
        entry = "[INDEX.md](ui-design/INDEX.md)" if path.name == "ui-design" else "-"
        body.append([f"`{path.name}/`", TOOL_PURPOSE[path.name], entry])
    out += table(["Folder", "Purpose", "Index"], body) + ["", f"## Skills ({len(skills)})", ""]
    out += table(["Skill", "What it does"],
                 [[f"[{fm['name']}](.claude/skills/{p.parent.name}/SKILL.md)", first_sentence(fm["description"])]
                  for fm, p in skills]) + ["", f"## Agents ({len(agents)})", ""]
    out += table(["Agent", "What it does"],
                 [[f"[{fm['name']}](.claude/agents/{p.name})", first_sentence(fm["description"])]
                  for fm, p in agents]) + [""]
    return "\n".join(out)


def missing_from_root(text):
    skills, agents = collect_entries()
    return [fm["name"] for fm, _ in skills + agents if f"[{fm['name']}]" not in text]


def read_text(path):
    return path.read_text(encoding="utf-8") if path.exists() else None


def main():
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except AttributeError:
            pass
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify both indexes are current; write nothing")
    args = parser.parse_args()
    try:
        generated = {TOOL_INDEX: build_tool_index() + "\n", ROOT_INDEX: build_root_index() + "\n"}
        if args.check:
            problems = []
            for path, content in generated.items():
                current = read_text(path)
                name = path.relative_to(REPO_ROOT).as_posix()
                if current is None:
                    problems.append(f"{name} is missing")
                elif current != content:
                    problems.append(f"{name} is stale")
            root_text = read_text(ROOT_INDEX)
            if root_text is not None:
                absent = missing_from_root(root_text)
                if absent:
                    problems.append("INDEX.md does not list: " + ", ".join(absent))
            if problems:
                raise IndexError_("; ".join(problems) + f". Regenerate with: {REGENERATE}")
        else:
            for path, content in generated.items():
                path.write_text(content, encoding="utf-8", newline="\n")
    except (IndexError_, OSError, KeyError) as exc:
        print(f"generate-index: {exc}", file=sys.stderr)
        return 2
    print("Indexes are current." if args.check else "Generated ui-design/INDEX.md and INDEX.md.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
